baseURL = 'https://janw.name/'
languageCode = 'en-us'
title = 'janw.name'
theme = 'janw'

[params]
subtitle = 'Personal Blog and Portfolio of Jan Wolff'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.main]]
  name = 'whoami'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Blog'
  url = '/posts/'
  weight = 100
[[menu.main]]
  name = 'Projects'
  url = '/projects/'
  weight = 120
[[menu.main]]
  name = 'Tools'
  url = '/tools/'
  weight = 120
