baseURL = 'https://janw.name/'
languageCode = 'en-us'
title = 'janw.name'
theme = 'janw'

[params]
subtitle = 'personal blog and portfolio of jan wolff'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.main]]
  name = 'whoami'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'blog'
  url = '/posts/'
  weight = 100
[[menu.main]]
  name = 'projects'
  url = '/projects/'
  weight = 120
